stages:
  - build
  - deploy
variables:
  IMAGE_REPO: dimgordi/db-demo-k8s-php-redis
  KUBE_NAMESPACE: development
build:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
    - echo "Building application Docker container..."
    - docker build -t ${IMAGE_REPO}:${CI_COMMIT_SHORT_SHA} .
    - docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD}
    - echo "Pushing to the Container Registry..."
    - docker push ${IMAGE_REPO}:${CI_COMMIT_SHORT_SHA}
deploy:
  stage: deploy
  environment:
    name: demo
  image:
    name: dtzar/helm-kubectl
  script:
    - helm init --client-only
    - helm upgrade
      --install dmitry-guest-book-php
      --tiller-namespace development 
      --namespace development 
      --wait 
      --set replicaCount=3
      --set image.tag=${CI_COMMIT_SHORT_SHA}
      ./helm-chart/