stages:
  - deploy
deploy:
  stage: deploy
  image:
    name: dtzar/helm-kubectl
  script:
    - kubectl get nodes
    - helm init --client-only
    - helm upgrade
      --install dmitry-guest-book-php 
      --namespace development 
      --wait 
      --set replicaCount=3
      ./helm-data/