stages:
  - deploy
variables:
  KUBE_NAMESPACE: development
deploy:
  stage: deploy
  environment:
    name: demo
  image:
    name: dtzar/helm-kubectl
  script:
    - helm init --client-only
    - helm upgrade
      --install dmitry-guest-book-php
      --tiller-namespace development 
      --namespace development 
      --wait 
      --set replicaCount=3
      ./helm-chart/